# Generated by Django 5.2.4 on 2025-08-02 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید به صورت +989XXXXXXXXX باشد', regex='^\\+?1?\\d{9,15}$')])),
                ('subject', models.CharField(choices=[('project', 'درخواست پروژه'), ('collaboration', 'همکاری'), ('consultation', 'مشاوره'), ('other', 'سایر'), ('idea', 'نظرات')], default='other', max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_replied', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('frontend', 'فرانت اند'), ('backend', 'بک اند'), ('fullstack', 'فول استک'), ('mobile', 'موبایل'), ('database', 'دیتابیس'), ('other', 'سایر')], default='other', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت ها',
            },
        ),
        migrations.AlterModelOptions(
            name='projectname',
            options={'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه ها'},
        ),
        migrations.AlterModelOptions(
            name='webcategory',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='youridea',
            options={'verbose_name': 'ایده', 'verbose_name_plural': 'ایده ها'},
        ),
        migrations.AddField(
            model_name='projectname',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='projectname',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AddField(
            model_name='projectname',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='projectname',
            name='projshortdetail',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='projectname',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AddField(
            model_name='projectname',
            name='status',
            field=models.CharField(choices=[('completed', 'تکمیل شده'), ('in_progress', 'در حال انجام'), ('pending', 'در انتظار')], default='completed', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='projectname',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AddField(
            model_name='webcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='projectname',
            name='projdetail',
            field=models.CharField(max_length=2000),
        ),
    ]
