# Generated by Django 5.2.4 on 2025-08-06 08:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='بیوگرافی')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile_avatars/', verbose_name='تصویر پروفایل')),
                ('phone_number', models.CharField(blank=True, max_length=17, verbose_name='شماره تلفن')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='عنوان شغلی')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='شرکت')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='موقعیت جغرافیایی')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
                ('github', models.URLField(blank=True, verbose_name='گیت\u200cهاب')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید در فرمت صحیح وارد شود.', regex='^\\+?1?\\d{9,15}$')], verbose_name='تلفن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
